version: "3.9"
services:
  front:
    build:
      context: ./clos-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  back:
    build:
      context: ./clos-backend
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
